### ISSUE TITLE
Overriding nested config entries

### ISSUE THREAD

**Issue by Phoenix1708** [vngrs/konfig#17]
If I have following 2 sections within my YAML config file, i.e. default and test. The "service" entry doesn't gets overrides by the "service" entry in test if I set NODE_ENV to test, only the "loglevel" gets overridden. Is this the issue of nested entries or something else ?

Thank you very much for your consideration of my issue.

``
default:
  loglevel: info
  service:
    chilld_entry_1: 'type'
    chilld_entry_2:
      chilld_2_child_entry_1: 'value in default config'
      chilld_2_child_entry_2: 'some other value in default config'
    chilld_entry_3: 1
    chilld_entry_4:
      chilld_entry_4_chilld_entry: 1

test:
  loglevel: debug
  service:
     chilld_entry_1: 'test type'
    chilld_entry_2:
      chilld_2_child_entry_1: 'value in test config'
      chilld_2_child_entry_2: 'some other value in test config'
    chilld_entry_3: 1000000
    chilld_entry_4:
      chilld_entry_4_chilld_entry: 10000000
``

**Comment by alidavut** [comment]
I have tested your config file. The result looks correct.

Default log:
```bash
node app.js
```

```js
{ app:
   { loglevel: 'info',
     service:
      { chilld_entry_1: 'type',
        chilld_entry_2: [Object],
        chilld_entry_3: 1,
        chilld_entry_4: [Object] } } }
```

Test Environment log :
```bash
NODE_ENV=test node app.js
```

```js
{ app:
   { loglevel: 'debug',
     service:
      { chilld_entry_1: 'test type',
        chilld_entry_2: [Object],
        chilld_entry_3: 1000000,
        chilld_entry_4: [Object] } } }
```

**Comment by Phoenix1708** [comment]
OK. For nested objects, It actually add the new property from the nested entry with same name in ```test``` section into the corresponding entry in ```default``` section rather than completely override the nested entry. so

```
default:
  loglevel: info
  service:
    chilld_entry_1: 'type'
    chilld_entry_2:
      chilld_2_child_entry_1: 'value in default config'
      chilld_2_child_entry_2: 'some other value in default config'

test:
  loglevel: debug
  service:
    chilld_entry_1: 'test type'
    chilld_entry_2:
      chilld_2_completely_different_entry: 'some value, could be object'
```

This ``` chilld_2_completely_different_entry``` will be added into ```chilld_entry_2```, based on my test (sorry for being blind when I raise the issue)

I guess maybe there could be an option to specify whether to append or override, since there could be cases where we need one set of config data for development and one set for testing or something else. Sorry for the misleading example I give at the first time.
