### ISSUE TITLE
Not parsing the example yml

### ISSUE THREAD

**Issue by niksmac** [vngrs/konfig#19]
When i create `config/app.yml` with 
```

default:
    port: 3000
    cache_assets: true
    secret_key: 7EHDWHD9W9UW9FBFB949394BWYFG8WE78F

development:
    cache_assets: false

test:
    port: 3001

production: &production
    port: #{process.env.PORT}
    secret_key: 3F8RRJR30UHERGUH8UERHGIUERHG3987GH8

```

And try 

```
global.config = require('konfig')()
console.log(config);
```

I get only this 

```
› node index.js
{ app:
   { port: 3000,
     cache_assets: false,
     secret_key: '7EHDWHD9W9UW9FBFB949394BWYFG8WE78F' } }
```

node v6.6.0
